export const rawQuestions = [
  {
    type: "multiStatement" as const,
    image: "",
    question: "নিচের কোনটি সত্য?",
    statements: [
      "i. পৃথিবীতে আবিষ্কৃত মৌলিক পদার্থ $118$ টি",
      "ii. কৃত্রিম মৌল $20$ টি",
      "iii. মানবদেহে $26$ রকমের মৌলিক পদার্থ আছে",
    ],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "i, ii & iii"],
    correctAnswer: "i, ii & iii",
  },
  {
    type: "normal" as const,
    image: "",
    question: "চক ভাঙলে কোন মৌলটি পাওয়া যাবে না?",
    options: ["C", "Ca", "S", "O"],
    correctAnswer: "S",
  },
  {
    type: "multiStatement" as const,
    image: "",
    question: "নিচের কোনটি হাইড্রোজেনের আইসোটোপ?",
    statements: ["i. প্রোটিয়াম", "ii. ডিউটেরিয়াম", "iii. ট্রিটিয়াম"],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "i, ii & iii"],
    correctAnswer: "i, ii & iii",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোনটি সঠিক?",
    options: [
      "$O_2$ যৌগের অণু",
      "$CO_2$ মৌলের অণু",
      "অণু গঠনে কমপক্ষে দুটি পরমাণু দরকার",
      "সকল অণুই যৌগ",
    ],
    correctAnswer: "অণু গঠনে কমপক্ষে দুটি পরমাণু দরকার",
  },
  {
    type: "normal" as const,
    image: "",
    question: "টাংস্টেন ধাতুর প্রতীক কোনটি?",
    options: ["T", "Ta", "Y", "W"],
    correctAnswer: "W",
  },
  {
    type: "normal" as const,
    image: "",
    question: "এক অণু সালফিউরিক এসিডে কতটি সালফার পরমাণু থাকে?",
    options: ["7", "1", "0", "2"],
    correctAnswer: "1",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোনটি পরমাণুর মৌলিক কণিকা?",
    options: ["পজিট্রন", "মেসন", "আলফা", "প্রোটন"],
    correctAnswer: "প্রোটন",
  },
  {
    type: "normal" as const,
    image: "",
    question: "কোনটি সঠিক নয়?",
    options: [
      "ইলেকট্রন, প্রোটন ও নিউট্রনের তুলনায় $1/1840$ গুন ভারী",
      "ইলেকট্রনের আধান $-1.60 \\times 10^{-19} \\text{C}$",
      "ইলেকট্রনের আপেক্ষিক আধান $-1$",
      "ইলেকট্রনের প্রকৃত ভর $9.11 \\times 10^{-31} \\text{kg}$",
    ],
    correctAnswer: "ইলেকট্রন, প্রোটন ও নিউট্রনের তুলনায় $1/1840$ গুন ভারী",
  },
  {
    type: "normal" as const,
    image: "",
    question: "মৌলের পরিচয় বহন করে কোন কণিকা?",
    options: ["ইলেকট্রন", "প্রোটন", "নিউট্রন", "ভর"],
    correctAnswer: "প্রোটন",
  },
  {
    type: "normal" as const,
    image: "",
    question: "পরমাণু চার্জ নিরপেক্ষ। কারণ -",
    options: [
      "প্রোটন সংখ্যা = নিউট্রন সংখ্যা",
      "ইলেকট্রন সংখ্যা = নিউট্রন সংখ্যা",
      "প্রোটন সংখ্যা = ইলেকট্রন সংখ্যা",
      "ভরসংখ্যা = প্রোটন সংখ্যা + নিউট্রন সংখ্যা",
    ],
    correctAnswer: "প্রোটন সংখ্যা = ইলেকট্রন সংখ্যা",
  },
  {
    type: "normal" as const,
    image: "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image//Na.jpg",
    question: "উপরের মৌলটির $n - e = ??$",
    options: ["2", "1", "10", "12"],
    correctAnswer: "1",
  },
  {
    type: "normal" as const,
    image: "",
    question: "পরমাণুর গঠন সম্পর্কে মডেলটি রাদারফোর্ড কত সালে প্রদান করেন?",
    options: ["1897", "1913", "1911", "1932"],
    correctAnswer: "1911",
  },
  {
    type: "normal" as const,
    image:
      "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image//ruthurford.jpg",
    question: "উপরের মডেলটিতে নিচের কোন কথাটি বলা হয় নি?",
    options: [
      "পরমাণুর অধিকাংশ স্থান ফাঁকা",
      "পরমাণু সামগ্রিকভাবে চার্জ শূন্য",
      "নিউক্লিয়াসের ভরই পরমাণুর ভর",
      "পরমাণুতে ইলেকট্রন নির্দিষ্ট কক্ষপথে ঘুরে",
    ],
    correctAnswer: "পরমাণুতে ইলেকট্রন নির্দিষ্ট কক্ষপথে ঘুরে",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোনটি রাদার্ফোর্ড পরমাণু মডেলের সীমাবদ্ধতা?",
    options: [
      "কক্ষপথের আকার ও আকৃতি কথা বলেন নি",
      "চার্জযুক্ত বস্তুর সাথে চার্জহীন বস্তু্র তুলনা করেছেন",
      "একের অধিক ইলেকট্রন কক্ষপথে কিভাবে পরিভ্রমন করে তা বলেন নি",
      "পরমাণুর বর্ণালির কোনো ব্যাখ্যা পাওয়া যায় না",
    ],
    correctAnswer: "সবগুলো",
  },
  {
    type: "normal" as const,
    image: "",
    question: "বোর পরমাণু মডেলের স্বীকার্য নয় কোনটি?",
    options: [
      "শক্তিস্তর সম্পর্কিত ধারণা",
      "কৌণিক ভরবেগ সম্পর্কিত ধারণা",
      "শক্তির বিকিরণ সম্পর্কিত ধারণা",
      "উপকক্ষপথ সম্পর্কিত ধারণা",
    ],
    correctAnswer: "উপকক্ষপথ সম্পর্কিত ধারণা",
  },
  {
    type: "normal" as const,
    image: "",
    question: "'N' শক্তিস্তরে সর্বোচ্চ কয়টি ইলেকট্রন থাকতে পারে?",
    options: ["32", "8", "18", "স্যার আমি জানি না"],
    correctAnswer: "32",
  },
  {
    type: "normal" as const,
    image: "",
    question: "$^{21}\\text{Sc}$ মৌলটির 'N' শক্তিস্তরে কয়টি ইলেকট্রন আছে?",
    options: ["11", "3", "2", "1"],
    correctAnswer: "2",
  },
  {
    type: "normal" as const,
    image: "",
    question: "৩য় শক্তিস্তরে সর্বোচ্চ কয়টি অরবিটাল থাকতে পারে?",
    options: ["9", "3", "16", "18"],
    correctAnswer: "9",
  },
  {
    type: "normal" as const,
    image: "",
    question: "$n$ এর মানের জন্য $l$ এর মান হবে?",
    options: ["$2n+1$", "$n-1$", "$0 \\text{ to } n-1$", "$2(2n+1)$"],
    correctAnswer: "$0 \\text{ to } n-1$",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোনটি সত্য?",
    options: [
      "উপশক্তিস্তরে অরবিটাল সংখ্যা বের করার সূত্র $(2l+1)$",
      "প্রতিটি উপশক্তিস্তরে ইলেকট্রন সংখ্যা বের করার সূত্র $2(2l+1)$",
      "প্রতিটি অরবিটালে সর্বোচ্চ দুটি করে ইলেকট্রন থাকতে পারে",
      "$^{19}\\text{K}$ এর ১৯ তম ইলেকট্রনটি 4s অরবিটালে থাকে",
    ],
    correctAnswer: "$^{19}\\text{K}$ এর ১৯ তম ইলেকট্রনটি 4s অরবিটালে থাকে",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোন অরবিটালে ইলেকট্রন আগে প্রবেশ করে?",
    options: ["4p", "3d", "5s", "1f"],
    correctAnswer: "5s",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোন অরবিটাল দুটির শক্তি সমান?",
    options: ["5f, 7s", "4s, 3p", "3f, 6s", "4d, 3f"],
    correctAnswer: "5f, 7s",
  },
  {
    type: "normal" as const,
    image: "",
    question: "$^{26}\\text{Fe}^{3+}$ এ 3d অরবিটালে কয়টি ইলেকট্রন থাকে?",
    options: ["6", "8", "4", "3"],
    correctAnswer: "5",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোন ইলেকট্রন বিন্যাসটি সঠিক?",
    options: [
      "Cr(24) = $1s^22s^22p^63s^23p^63d^44s^2$",
      "Cu(29) = $1s^22s^22p^63s^23p^63d^94s^2$",
      "K(19) = $1s^22s^22p^63s^23p^63d^2$",
      "Fe(26) = $1s^22s^22p^63s^23p^63d^64s^2$",
    ],
    correctAnswer: "Fe(26) = $1s^22s^22p^63s^23p^63d^64s^2$",
  },
  {
    type: "normal" as const,
    image: "",
    question: "নিচের কোন জোড়ার মৌলদ্বয় পরস্পরের আইসোটোপ?",
    options: ["Te-127, I-127", "C-14, O-16", "Pb-204, Hg-204", "S-32, S-30"],
    correctAnswer: "S-32, S-30",
  },
  {
    type: "normal" as const,
    image: "",
    question: "ট্রিট্রিয়ামে কয়টি নিউট্রন আছে?",
    options: ["1 টি", "2 টি", "4 টি", "3 টি"],
    correctAnswer: "2 টি",
  },
  {
    type: "normal" as const,
    image: "",
    question: "$^{238}\\text{U}$ এর একটি পরমাণুর প্রকৃত ভর কত?",
    options: [
      "$4.482 \\times 10^{-23}$",
      "$3.16 \\times 10^{-23}$",
      "$2.99 \\times 10^{-23}$",
      "$3.95 \\times 10^{-22}$",
    ],
    correctAnswer: "$3.95 \\times 10^{-22}$",
  },
  {
    type: "normal" as const,
    image: "",
    question:
      "প্রকৃতিতে কপারের দুটি আইসোটোপ $^{63}\\text{Cu}$ এবং $^{65}\\text{Cu}$। কপারের গড় পারমাণবিক আপেক্ষিক ভর $63.5$ হলে প্রকৃতিতে $^{63}\\text{Cu}$ শতকরা পরিমাণ কত?",
    options: ["60 %", "25 %", "স্যার আমি একজন ফাঁকিবাজ ছাত্র", "75 %"],
    correctAnswer: "75 %",
  },
  {
    type: "normal" as const,
    image: "",
    question: "$\\text{HClO}_4$ এর আণবিক ভর কত?",
    options: ["63", "100", "71", "100.5"],
    correctAnswer: "100.5",
  },
  {
    type: "normal" as const,
    image: "",
    question: "আইসোটোপের ক্ষেত্রে কোনটি সঠিক?",
    options: [
      "$^{131}\\text{I}$ থাইরয়েড ক্যান্সার নিরাময়ে ব্যবহার করা হয়",
      "ইরিডিন আইসোটোপ ব্রেইন ক্যান্সার নিরাময়ে ব্যবহার করা হয়",
      "$^{32}\\text{P}$ রক্তের লিউকোমিয়া রোগের চিকিৎসায় ব্যবহার করা হয়",
      "পৃথিবীর বয়স নির্ণয়ে $^{12}\\text{C}$ ব্যবহার করা হয়",
    ],
    correctAnswer: "$^{131}\\text{I}$ থাইরয়েড ক্যান্সার নিরাময়ে ব্যবহার করা হয়",
  },
];
