export const rawQuestions = [
  {
    type: "normal",
    image: "",
    question: "সকল পদার্থ কয়টি অবস্থায় থাকতে পারে?",
    options: ["৩", "৪", "৫", "৬"],
    correctAnswer: "৩",
  },
  {
    type: "normal",
    image: "",
    question: "কক্ষ তাপমাত্রা বলতে কোন তাপমাত্রাকে বোঝানো হয়?",
    options: ["0°C", "25°C", "100°C", "350°C"],
    correctAnswer: "25°C",
  },
  {
    type: "multiStatement",
    image: "",
    question: "কঠিন পদার্থের ক্ষেত্রে কোনটি সঠিক?",
    statements: [
      "i. নির্দিষ্ট আকার ও আয়তন আছে",
      "ii. চাপ প্রয়োগে সংকুচিত হয়",
      "iii. আন্তকণা আকর্ষণ বল বেশি",
    ],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "i, ii & iii"],
    correctAnswer: "i & iii",
  },
  {
    type: "normal",
    image: "",
    question: "তাপ প্রয়োগে __।",
    options: [
      "কঠিন পদার্থের আয়তন বৃদ্ধি হয় না",
      "তরল পদার্থের আয়তন কমে যায়",
      "গ্যাসীয় পদার্থের আয়তন সামান্য বৃদ্ধি পায়",
      "কোনটিই নয়",
    ],
    correctAnswer: "গ্যাসীয় পদার্থের আয়তন সামান্য বৃদ্ধি পায়",
  },
  {
    type: "normal",
    image: "",
    question: "কণার গতিতত্ত্বের ক্ষেত্রে কোনটি সঠিক নয়?",
    options: [
      "কঠিন পদার্থের কণাগুলোর আন্তঃআণবিক শক্তি বেশি, গতিশক্তি নেই",
      "তাপ প্রয়োগে কঠিন পদার্থের কণাগুলোর গতিশক্তি বৃদ্ধি পায়",
      "গ্যাসীয় পদার্থের কণাগুলোর গতিশক্তি অনেক কম",
      "তরল পদার্থের কণাগুলো চলাচল করতে পারে",
    ],
    correctAnswer: "গ্যাসীয় পদার্থের কণাগুলোর গতিশক্তি অনেক কম",
  },
  {
    type: "normal",
    image: "",
    question: "কোন অবস্থায় পদার্থের ব্যপন হার বেশি হয়?",
    options: ["কঠিন", "তরল", "বায়বীয়"],
    correctAnswer: "বায়বীয়",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোন গ্যাসটির ব্যাপন হার সবচেয়ে বেশি?",
    options: ["O₂", "CH₄", "N₂", "Cl₂"],
    correctAnswer: "CH₄",
  },
  {
    type: "normal",
    image: "",
    question: "সিএনজি গ্যাসে মূলত কোন গ্যাস থাকে?",
    options: ["মিথেন", "প্রোপেন", "বিউটেন", "অক্সিজেন"],
    correctAnswer: "মিথেন",
  },
  {
    type: "normal",
    image:
      "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image//h2o.jpg",
    question: "AB রেখাকে বলা হয়?",
    options: ["গলানাংক রেখা", "বাষ্পীয় রেখা", "স্ফুটনাংক রেখা", "ঘনীভবন রেখা"],
    correctAnswer: "বাষ্পীয় রেখা",
  },
  {
    type: "normal",
    image: "",
    question: "মোম অক্সিজেনের সাথে বিক্রিয়া করে নিচের কোনটি উৎপন্ন করে না?",
    options: ["জলীয়বাষ্প", "মিথেন", "কার্বন ডাই অক্সাইড", "তাপ"],
    correctAnswer: "মিথেন",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি সঠিক নয়?",
    options: [
      "বরফের গলানাংক 0°C",
      "বিশুদ্ধ সালফারের গলানাংক 115°C",
      "পানির স্ফুটনাংক 100°C",
      "খাবার লবণের গলানাংক 801°C",
    ],
    correctAnswer: "খাবার লবণের গলানাংক 801°C",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি উর্ধ্বপাতিত পদার্থ নয়?",
    options: ["I₂", "AlCl₃", "C₁₀H₈", "NaCl"],
    correctAnswer: "NaCl",
  },
];
