export const rawQuestions = [
  {
    type: "multiStatement",
    image: "",
    question: "রসায়ন শাখায় কোন বিষয়টি নিয়ে আলোচনা করা হয়?",
    statements: [
      "i. পদার্থের গঠন",
      "ii. পদার্থের ধর্ম",
      "iii. পদার্থের পরিবর্তন",
    ],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "i, ii & iii"],
    correctAnswer: "i, ii & iii",
  },
  {
    type: "normal",
    image: "",
    question: "কয়লার প্রধান উপাদান কোনটি?",
    options: ["C", "S", "H", "O"],
    correctAnswer: "C",
  },
  {
    type: "normal",
    image: "",
    question: "পৃথিবীতে প্রথম ব্যবহৃত ধাতু কোনটি?",
    options: ["Ag", "Cu", "Au", "Zn"],
    correctAnswer: "Cu",
  },
  {
    type: "normal",
    image: "",
    question: "ব্রোঞ্জ কোন ধাতুদ্বয়ের সংকর?",
    options: ["Ag + Sn", "Cu + Sn", "Au + Ag", "Sn + Zn"],
    correctAnswer: "Cu + Sn",
  },
  {
    type: "normal",
    image: "",
    question: "ডেমোক্রিটাস পদার্থের ক্ষুদ্রতম কণার নাম কি?",
    options: ["Atom", "Particle", "Molecule", "Loads"],
    correctAnswer: "Atom",
  },
  {
    type: "normal",
    image: "",
    question: "মধ্যযুগে আরবের রসায়ন চর্চাকে কী বলা হত?",
    options: ["Chemistry", "Alchemy", "Magic", "Change"],
    correctAnswer: "Alchemy",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি সঠিক?",
    options: [
      "Kimi --> Al-Chimia --> Alchemy",
      "Alchemy --> Al-Chimia --> Kimi",
      "Al-Chimia --> Kimi --> Alchemy",
      "Alchemy --> Kimi --> Alchemy",
    ],
    correctAnswer: "Kimi --> Al-Chimia --> Alchemy",
  },
  {
    type: "normal",
    image: "",
    question: "রসায়নের জনক কে?",
    options: [
      "জাবির ইবনে হাইয়ান",
      "রবার্ট বয়েল",
      "জন ডাল্টন",
      "অ্যান্টনি ল্যাভসিয়ে",
    ],
    correctAnswer: "জাবির ইবনে হাইয়ান",
  },
  {
    type: "normal",
    image: "",
    question: "আধুনিক রসায়নের জনক কে?",
    options: [
      "জাবির ইবনে হাইয়ান",
      "রবার্ট বয়েল",
      "জন ডাল্টন",
      "অ্যান্টনি ল্যাভসিয়ে",
    ],
    correctAnswer: "অ্যান্টনি ল্যাভসিয়ে",
  },
  {
    type: "normal",
    image: "",
    question: "আম টকের জন্য কোন এসিড দায়ী?",
    options: ["সাকসিনিক এসিড", "ম্যালেয়িক এসিড", "গ্লুকোজ", "A & B"],
    correctAnswer: "ম্যালেয়িক এসিড",
  },
  {
    type: "normal",
    image: "",
    question: "পৃথিবী জন্মের সময় কেমন ছিল?",
    options: ["উত্তপ্ত", "খুবই শীতল", "শীতল", "খুবই উত্তপ্ত"],
    correctAnswer: "খুবই উত্তপ্ত",
  },
  {
    type: "normal",
    image: "",
    question: "আম মিষ্টির জন্য দায়ী কোনটি?",
    options: ["Fructose", "ম্যালেয়িক এসিড", "Gulucose", "A & C"],
    correctAnswer: "Fructose",
  },
  {
    type: "normal",
    image: "",
    question: "কেরোসিনের দহনে উৎপন্ন হয় কি কি?",
    options: ["কার্বন ডাই অক্সাইড", "জলীয় বাষ্প", "তাপ ও আলো", "সবগুলো"],
    correctAnswer: "সবগুলো",
  },
  {
    type: "normal",
    image: "",
    question: "পেট ব্যথার জন্য দায়ী কোনটি?",
    options: [
      "হাইড্রোক্লোরিক এসিড",
      "সালফিউরিক এসিড",
      "ম্যাগনেসিয়াম ক্লোরাইড",
      "সোডিয়াম ক্লোরাইড",
    ],
    correctAnswer: "হাইড্রোক্লোরিক এসিড",
  },
  {
    type: "normal",
    image: "",
    question: "এন্টাসিডে থাকে কোনটি?",
    options: [
      "সাকসিনিক এসিড",
      "ম্যাগনেসিয়াম হাইড্রোক্সাইড",
      "অ্যালুমিনায়াম হাইড্রোক্সাইড",
      "B & C",
    ],
    correctAnswer: "B & C",
  },
  {
    type: "normal",
    image: "",
    question: "বায়ুর প্রধান উপাদান কোনটি?",
    options: ["অক্সিজেন", "হাইড্রোজেন", "নাইট্রোজেন", "কার্বন ডাই অক্সাইড"],
    correctAnswer: "নাইট্রোজেন",
  },
  {
    type: "normal",
    image: "",
    question: "কাগজের প্রধান উপাদান কোনটি?",
    options: ["সেলুলোজ", "এসিড", "লবণ", "সুক্রোজ"],
    correctAnswer: "সেলুলোজ",
  },
  {
    type: "multiStatement",
    image: "",
    question: "সেলুলোজ পাওয়া যায় নিচের কোনটিতে?",
    statements: ["i. বাঁশ", "ii. আখ", "iii. কচুরি পানা"],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "i, ii & iii"],
    correctAnswer: "i, ii & iii",
  },
  {
    type: "normal",
    image:
      "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image//photosynthesis.jpg",
    question:
      "উপরের বিক্রিয়াটি সালোকসংশ্লেষনের সঠিক বিক্রিয়া কি'না?(সত্য/মিথ্যা)",
    options: ["সত্য", "মিথ্যা"],
    correctAnswer: "সত্য",
  },
  {
    type: "normal",
    image: "",
    question: "চকের রাসায়নিক সংকেত কোনটি?",
    options: ["CaSO4", "ZnCO3", "CaCO3", "MgCO3"],
    correctAnswer: "CaSO4",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি ভারী ধাতু নয়?",
    options: ["লেড", "ক্রোমিয়াম", "মার্কারি", "কপার"],
    correctAnswer: "ক্রোমিয়াম",
  },
  {
    type: "normal",
    image: "",
    question: "রসায়ন গবেষণা প্রকিয়ার প্রথম ধাপ কোনটি?",
    options: ["বিষয় নির্বাচন", "পরীক্ষণ", "ফলাফল", "তথ্য সংগ্রহ"],
    correctAnswer: "বিষয় নির্বাচন",
  },
  {
    type: "normal",
    image: "",
    question: "রসায়ন গবেষণা প্রকিয়ার ধাপ কয়টি?",
    options: ["৫ টি", "৬ টি", "৭ টি", "৪ টি"],
    correctAnswer: "৫ টি",
  },
  {
    type: "normal",
    image:
      "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image//flowchart.jpg",
    question: "?? চিহ্নিত স্থানে কি হবে?",
    options: ["বিষয় নির্বাচন", "পরীক্ষণ", "ফলাফল", "তথ্য সংগ্রহ"],
    correctAnswer: "তথ্য সংগ্রহ", // User can fill manually
  },
  {
    type: "normal",
    image: "",
    question: "রসায়ন ল্যাবে নিরাপদ পোশাকের নাম কি?",
    options: ["শার্ট", "অ্যাপ্রোন", "মাস্ক", "কোর্ট"],
    correctAnswer: "অ্যাপ্রোন",
  },
  {
    type: "normal",
    image: "",
    question: "চোখকে রক্ষা করার জন্য কোনটি ব্যবহার করবে?",
    options: ["সেফটি গুগলস", "অ্যাপ্রোন", "মাস্ক", "হ্যান্ড গ্লাভস"],
    correctAnswer: "সেফটি গুগলস",
  },
  {
    type: "multiStatement",
    image: "",
    question: "নিচের কোনটি বিস্ফোরক পদার্থ?",
    statements: ["i. টিএনটি", "ii. জৈব পার অক্সাইড", "iii. নাইট্রোগ্লিসারিন"],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "i, ii & iii"],
    correctAnswer: "i, ii & iii",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি দাহ্য পদার্থ?",
    options: ["অ্যালকোহল", "ইথার", "বেনজিন", "A & B"],
    correctAnswer: "A & B",
  },
  {
    type: "normal",
    image:
      "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image//toxic.jpg",
    question: "উপরের সাংকেতিক চিহ্নটি দ্বারা বোঝানো হয় কোনটি?",
    options: [
      "বিষাক্ত পদার্থ",
      "বিস্ফোরক পদার্থ",
      "উত্তেজক পদার্থ",
      "দাহ্য পদার্থ",
    ],
    correctAnswer: "বিষাক্ত পদার্থ",
  },
  {
    type: "multiStatement",
    image: "",
    question: "নিচের কোনটি বিষাক্ত পদার্থ নয়?",
    statements: ["i. বেনজিন", "ii. ক্লোরোবেনজিন", "iii. মিথানল"],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["i & ii", "i & iii", "ii & iii", "কোনটিই নয়"],
    correctAnswer: "কোনটিই নয়",
  },
  {
    type: "normal",
    image: "",
    question: "নাইট্রাস অক্সাইড একটি __।",
    options: [
      "বিষাক্ত পদার্থ",
      "বিস্ফোরক পদার্থ",
      "উত্তেজক পদার্থ",
      "দাহ্য পদার্থ",
    ],
    correctAnswer: "বিস্ফোরক পদার্থ",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি স্বাস্থ ঝুঁকিপূর্ণ পদার্থ?",
    options: ["টলুইন", "জাইলিন", "বেনজিন", "সবগুলো"],
    correctAnswer: "সবগুলো",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোন চিহ্নটি তেজস্ক্রিয় পদার্থ প্রকাশ করে?",
    options: ["explosive.jpg", "radioactive.jpg", "toxic.jpg", "flammable.jpg"],
    correctAnswer: "radioactive.jpg",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি মিথ্যা?",
    options: [
      "ইউরেনিয়াম, রেডিয়াম তেজস্ক্রিয় পদার্থ",
      "লেড, মার্কারি পরিবেশের জন্য ক্ষতিকারক পদার্থ",
      "সালফিউরিক এসিড, সোডিয়াম হাইড্রোক্সাইড ক্ষত সৃষ্টিকারী পদার্থ",
      "কোনটিই নয়",
    ],
    correctAnswer: "কোনটিই নয়",
  },
];
