export const rawQuestions = [
  {
    type: "normal",
    image: "",
    question: "নিচের কোন উদাহরণটিতে পদার্থের ভৌত পরিবর্তন ঘটে না?",
    options: [
      "বরফ থেকে পানি হওয়া",
      "মোমের গলন",
      "কাগজ পোড়ানো",
      "লবণ ও পানি একসাথে মেশানো",
    ],
    correctAnswer: "কাগজ পোড়ানো",
  },
  {
    type: "normal",
    image: "",
    question: "অ্যালকোহল ও জৈব এসিড বিক্রিয়া করে উৎপন্ন করে কোনটি?",
    options: ["অ্যালকিন", "অ্যালকেন", "অ্যালকাইন", "এস্টার"],
    correctAnswer: "এস্টার",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি সত্য?",
    options: [
      "একমূখী বিক্রিয়ার ক্ষেত্রে বিক্রিয়া শুধু সামনের দিকে অগ্রসর হয়",
      "উভমূখী বিক্রিয়ার ক্ষেত্রে বিক্রিয়া একই সময়ে সম্মূখে ও পশ্চাৎ দিকে অগ্রসর হয়",
      "রাসায়নিক পরিবর্তনে নতুন গঠনের পদার্থ তৈরি হয়",
      "খোলা পাত্রে ক্যালসিয়াম কার্বনেটকে তাপ দিলে উভমূখী বিক্রিয়া ঘটে",
    ],
    correctAnswer:
      "উভমূখী বিক্রিয়ার ক্ষেত্রে বিক্রিয়া একই সময়ে সম্মূখে ও পশ্চাৎ দিকে অগ্রসর হয়",
  },
  {
    type: "normal",
    image: "",
    question:
      "হেবার প্রণালিতে নাইট্রোজেন + হাইড্রোজেন বিক্রিয়া ঘটিয়ে অ্যামোনিয়া তৈরি করা হয়, এই বিক্রিয়ায় বিক্রিয়া তাপ কত?",
    options: ["-192 kj/mol", "+192 kj/mol", "-92 kj/mol", "+92 kj/mol"],
    correctAnswer: "-92 kj/mol",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি রেডক্স বিক্রিয়া নয়?",
    options: [
      "Zn + H₂SO₄ = ZnSO₄ + H₂",
      "2FeCl₂ + Cl₂ = 2FeCl₃",
      "Al₂O₃ + 6HCl = 2AlCl₃ + 3H₂O",
      "2Na + Cl₂ = 2NaCl",
    ],
    correctAnswer: "Al₂O₃ + 6HCl = 2AlCl₃ + 3H₂O",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি সঠিক নয়?",
    options: [
      "বিক্রিয়কে Na এ জারণ সংখ্যা 0 উৎপাদে +1; এটিকে বিজারণ বিক্রিয়া বলে",
      "বিক্রিয়কে Mn এর জারণ সংখ্যা +7 এবং উৎপাদে +2; এটিকে জারণ বলে",
      "বিক্রিয়ক X এর জারণ সংখ্যা -1 এবং উৎপাদে -2; এটিকে বিজারণ বলে",
      "জারণ-বিজারণ একই সাথে ঘটে",
    ],
    correctAnswer:
      "বিক্রিয়ক X এর জারণ সংখ্যা -1 এবং উৎপাদে -2; এটিকে বিজারণ বলে",
  },
  {
    type: "normal",
    image: "",
    question: "K₂Cr₂O₇ এ Cr এর জারণ সংখ্যা কত?",
    options: ["+6", "-6", "+7", "-7"],
    correctAnswer: "+6",
  },
  {
    type: "normal",
    image: "",
    question: "H₂O₂ এ O এর জারণ সংখ্যা কত?",
    options: ["-1/2", "+1/2", "-1", "-2"],
    correctAnswer: "-1/2",
  },
  {
    type: "normal",
    image: "",
    question: "K₄Fe(CN)₆ এ O এর জারণ সংখ্যা কত?",
    options: ["-2", "+2", "-3", "+3"],
    correctAnswer: "-2",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি সঠিক নয়?",
    options: [
      "N₂ + 3H₂ = 2NH₃ → সংশ্লেষণ বিক্রিয়া",
      "NaCl + AgNO₃ = NaNO₃ + AgCl ↓ - অধঃক্ষেপণ বিক্রিয়া",
      "2H₂ + O₂ = 2H₂O → দহন বিক্রিয়া",
      "CaCO₃ → CaO + CO₂ - সংযোজন বিক্রিয়া",
    ],
    correctAnswer: "CaCO₃ → CaO + CO₂ - সংযোজন বিক্রিয়া",
  },
  {
    type: "normal",
    image: "",
    question: "প্রশমন বিক্রিয়ায় প্রশমন তাপ কত?",
    options: ["+57.3 kj", "-57.3 kj", "+92 kj", "-92 kj"],
    correctAnswer: "-57.3 kj",
  },
  {
    type: "normal",
    image: "",
    question: "AlCl₃ + H₂O → Al(OH)₃ + 3HCl; বিক্রিয়াটি একটি,",
    options: [
      "আদ্রবিশ্লেষণ বিক্রিয়া",
      "পানি বিশ্লেষণ বিক্রিয়া",
      "অধঃক্ষেপণ বিক্রিয়া",
      "সমাণুকরণ বিক্রিয়া",
    ],
    correctAnswer: "অধঃক্ষেপণ বিক্রিয়া",
  },
  {
    type: "normal",
    image: "",
    question: "ইউরিয়ার সংকেত কি?",
    options: ["NH₄CNO", "N₂H-CO-N₂H", "NH₃", "H₂N-CO-H₂N"],
    correctAnswer: "NH₄CNO",
  },
  {
    type: "normal",
    image: "",
    question:
      "n(CH₂=CH₂) → (-CH₂-CH₂-)ₙ ; এই বিক্রিয়াটি ঘটার উপযুক্ত পরিবেশ কি?",
    options: [
      "প্রভাবক N₂, 200°C তাপমাত্রা, 1200 atm চাপ",
      "প্রভাবক O₂, 1200°C তাপমাত্রা, 200 atm চাপ",
      "প্রভাবক Fe, 200°C তাপমাত্রা, 1200 atm চাপ",
      "প্রভাবক O₂, 200°C তাপমাত্রা, 1200 atm চাপ",
    ],
    correctAnswer: "প্রভাবক N₂, 200°C তাপমাত্রা, 1200 atm চাপ",
  },
  {
    type: "normal",
    image: "",
    question: "মরিচার সংকেত কি?",
    options: ["Fe₃O₄", "FeO.nH₂O", "Fe₂O₃.nH₂O", "Al₂O₃.nH₂O"],
    correctAnswer: "Fe₂O₃.nH₂O",
  },
  {
    type: "normal",
    image: "",
    question: "কোনটি সঠিক?",
    options: [
      "Fe ধাতু Cu ও Al অপেক্ষা বেশিদিন টেকে",
      "মৌমাছি ও পিঁপড়ার হুলে একধরণের ক্ষারক থাকে",
      "শ্বসনে উৎপন্ন হয় অক্সিজেন গ্যাস ও বিপুল শক্তি",
      "Na ধাতু কেরোসিনের নিচে রেখে সংরক্ষণ করা হয়",
    ],
    correctAnswer: "Na ধাতু কেরোসিনের নিচে রেখে সংরক্ষণ করা হয়",
  },
  {
    type: "normal",
    image: "",
    question: "এন্টাসিডের প্রধান উপাদান কোনটি?",
    options: ["Al₂O₃", "HCl", "Mg(OH)₂", "Both A and C"],
    correctAnswer: "Both A and C",
  },
  {
    type: "normal",
    image: "",
    question: "বালির সংকেত কি?",
    options: ["SiO₂", "KCl", "Pb₃O₄", "N₂O"],
    correctAnswer: "SiO₂",
  },
  {
    type: "normal",
    image: "",
    question: "ভিনেগারের সংকেত কি?",
    options: ["4-10% CH₃COOH", "40% CH₃OH", "4-10% C₂H₅OH", "CH₃-COOH"],
    correctAnswer: "4-10% CH₃COOH",
  },
  {
    type: "normal",
    image: "",
    question: "নিচের কোনটি প্রতিস্থাপন বিক্রিয়া?",
    options: [
      "2H₂ + O₂ → 2H₂O",
      "CaCO₃ → CaO + CO₂",
      "AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)",
      "Zn + H₂SO₄ → ZnSO₄ + H₂",
    ],
    correctAnswer: "Zn + H₂SO₄ → ZnSO₄ + H₂",
  },
  {
    type: "normal",
    image: "",
    question: "অধিক সক্রিয় ধাতুর উপর কম সক্রিয় ধাতুর প্রলেপ দেয়াকে কি বলে?",
    options: [
      "ভলকানাইজিং",
      "গ্যালভানাইজিং",
      "ইলেকট্রোপ্লেটিং",
      "জানি না স্যার",
    ],
    correctAnswer: "গ্যালভানাইজিং",
  },
  {
    type: "normal",
    image:
      "https://codedbymojnu.github.io/ssc-mcq/ssc-chemistry/image/rasaynic_bikriya.png",
    question: "উদ্দীপকের কোন পাত্রে সবচেয়ে বেশি পরিমাণ বুদবুদ উৎপন্ন হবে?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "1",
  },
  {
    type: "normal",
    image: "",
    question:
      "N₂ + 3H₂ → 2NH₃; উভমূখী বিক্রিয়াটি সাম্যবস্থায় থাকাকালে তাপ প্রয়োগ করলে সাম্যের অবস্থা কিরূপ হবে?",
    options: [
      "বিক্রিয়াটি বামদিকে অগ্রসর হবে",
      "বিক্রিয়াটি ডানদিকে অগ্রসর হবে",
      "NH₃ উৎপাদন বাড়বে",
      "আমার দাদী জানেন, দাদীকে জিজ্ঞেস করতে হবে",
    ],
    correctAnswer: "বিক্রিয়াটি বামদিকে অগ্রসর হবে",
  },
  {
    type: "normal",
    image: "",
    question:
      "সাম্যাবস্থায় থাকা কালে নিচের কোন উভমূখী বিক্রিয়াটির ক্ষেত্রে চাপের প্রভাব আছে?",
    options: ["N₂(g) + O₂(g) = 2NO(g)", "2Pb(s) + O₂(g) = 2PbO"],
    correctAnswer: "N₂(g) + O₂(g) = 2NO(g)",
  },
  {
    type: "normal",
    image: "",
    question: "ZnO + C = Zn + CO; কোনটি বিজারক?",
    options: ["ZnO", "C", "Zn"],
    correctAnswer: "C",
  },
];
