export const rawQuestions = [
  // Normal Questions
  {
    type: "normal" as const,
    image: "/images/bangladesh-map.png",
    question: "বাংলাদেশের রাজধানী কোথায়?",
    options: ["চট্টগ্রাম", "রাজশাহী", "ঢাকা", "সিলেট"],
    correctAnswer: "ঢাকা",
  },
  {
    type: "normal" as const,
    image: "/images/bangladesh-national-flower.png",
    question: "বাংলাদেশের জাতীয় ফুল কোনটি?",
    options: ["গোলাপ", "শাপলা", "সূর্যমুখী", "জবা"],
    correctAnswer: "শাপলা",
  },
  {
    type: "normal" as const,
    image: "",
    question: "বাংলাদেশের স্বাধীনতা দিবস কোন তারিখে?",
    options: ["১৬ ডিসেম্বর", "২৬ মার্চ", "১৪ এপ্রিল", "২১ ফেব্রুয়ারি"],
    correctAnswer: "২৬ মার্চ",
  },
  {
    type: "normal" as const,
    image: "",
    question: "বাংলাদেশের প্রথম রাষ্ট্রপতি কে ছিলেন?",
    options: ["শেখ মুজিবুর রহমান", "সৈয়দ নজরুল ইসলাম", "আবু সাঈদ চৌধুরী", "জিল্লুর রহমান"],
    correctAnswer: "আবু সাঈদ চৌধুরী",
  },
  {
    type: "normal" as const,
    image: "/images/tajingdong.jpg",
    question: "বাংলাদেশের সর্বোচ্চ পর্বত শিখর কোনটি?",
    options: ["কেওক্রাডং", "তাজিংডং", "লালমাই", "মাধবপুর"],
    correctAnswer: "তাজিংডং",
  },
  {
    type: "passage" as const,
    passage:
      "বাংলাদেশ দক্ষিণ এশিয়ার একটি গুরুত্বপূর্ণ দেশ। এটি তিনটি বড় নদী দ্বারা গঠিত - পদ্মা, মেঘনা এবং ব্রহ্মপুত্র। এই নদীগুলি বাংলাদেশের অর্থনীতি এবং কৃষিতে গুরুত্বপূর্ণ ভূমিকা পালন করে। বাংলাদেশের মোট জনসংখ্যা প্রায় ১৭ কোটি।",
    questions: [
      {
        type: "multiStatement" as const,
        image: "",
        question: "বাংলাদেশের বড় নদী কোনটি?",
        statements: ["i. পদ্মা", "ii. মেঘনা", "iii. সুরমিলা"],
        questionEnd: "নিচের কোনটি সঠিক?",
        options: ["A. i & ii", "B. i & iii", "C. ii & iii", "D. শুধুমাত্র iii"],
        correctAnswer: "A. i & ii",
      },
      {
        type: "normal" as const,
        image: "/images/bangladesh-river.jpg",
        question: "নদীগুলি বাংলাদেশের কোন ক্ষেত্রে গুরুত্বপূর্ণ ভূমিকা পালন করে?",
        options: ["শুধুমাত্র পরিবহনে", "শুধুমাত্র মৎস্য শিল্পে", "অর্থনীতি এবং কৃষিতে", "শুধুমাত্র পর্যটনে"],
        correctAnswer: "অর্থনীতি এবং কৃষিতে",
      },
      {
        type: "normal" as const,
        image: "",
        question: "বাংলাদেশের মোট জনসংখ্যা প্রায় কত?",
        options: ["১০ কোটি", "১৫ কোটি", "১৭ কোটি", "২০ কোটি"],
        correctAnswer: "১৭ কোটি",
      },
    ],
  },
  {
    type: "normal" as const,
    image: "",
    question: "বাংলাদেশের জাতীয় সংগীত কে রচনা করেছেন?",
    options: ["রবীন্দ্রনাথ ঠাকুর", "কাজী নজরুল ইসলাম", "দ্বিজেন্দ্রলাল রায়", "সালিল চৌধুরী"],
    correctAnswer: "রবীন্দ্রনাথ ঠাকুর",
  },
  {
    type: "normal" as const,
    image: "",
    question: "বাংলাদেশের জাতীয় মুদ্রা কোনটি?",
    options: ["টাকা", "রুপি", "ডলার", "পাউন্ড"],
    correctAnswer: "টাকা",
  },
  {
    type: "multiStatement" as const,
    image: "",
    question: "বাংলাদেশের ভৌগোলিক বৈশিষ্ট্য সম্পর্কে কোনটি সঠিক?",
    statements: ["i. বাংলাদেশ একটি নদীমাতৃক দেশ", "ii. বাংলাদেশের বেশিরভাগ অঞ্চল সমতল", "iii. বাংলাদেশ সম্পূর্ণভাবে পর্বতময়"],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["A. i & ii", "B. i & iii", "C. ii & iii", "D. শুধুমাত্র iii"],
    correctAnswer: "A. i & ii",
  },
  {
    type: "normal" as const,
    image: "",
    question: "বাংলাদেশের বৃহত্তম শহর কোনটি?",
    options: ["চট্টগ্রাম", "খুলনা", "ঢাকা", "রাজশাহী"],
    correctAnswer: "ঢাকা",
  },
  {
    type: "passage" as const,
    image: "/images/bangladesh-language-movement.jpg",
    passage:
      "বাংলা ভাষা আন্দোলন ১৯৫২ সালে সংঘটিত হয়েছিল। এই আন্দোলনে অনেক শিক্ষার্থী তাদের প্রাণ দিয়েছিলেন। ২১ ফেব্রুয়ারি এই আন্দোলনের সবচেয়ে গুরুত্বপূর্ণ দিন। এই দিনটি এখন আন্তর্জাতিক মাতৃভাষা দিবস হিসেবে পরিচিত। এছাড়াও ১৯৬৯, ১৯৭১ সাল বাংলাদেশের গুরুত্বপূর্ণ বছর",
    questions: [
      {
        type: "multiStatement" as const,
        question: "বাংলাদেশের গুরুত্বপূর্ণ সাল?",
        statements: ["i. ১৯৫২", "ii. ১৯৬৯", "iii. ১৯৭১"],
        questionEnd: "নিচের কোনটি সঠিক?",
        options: ["A. i & ii", "B. i & iii", "C. ii & iii", "D. i, ii, & iii"],
        correctAnswer: "D. i, ii & iii",
      },
      {
        type: "normal" as const,
        image: "/images/bangladesh-language-movement.jpg",
        question: "২১ ফেব্রুয়ারি এখন কোন দিবস হিসেবে পরিচিত?",
        options: ["জাতীয় দিবস", "আন্তর্জাতিক মাতৃভাষা দিবস", "স্বাধীনতা দিবস", "বিজয় দিবস"],
        correctAnswer: "আন্তর্জাতিক মাতৃভাষা দিবস",
      },
    ],
  },
  {
    type: "normal" as const,
    image: "/images/bangladesh-constitution.jpg",
    question: "বাংলাদেশের সংবিধান কত সালে গৃহীত হয়েছিল?",
    options: ["১৯৭০", "১৯৭১", "১৯৭২", "১৯৭৩"],
    correctAnswer: "১৯৭২",
  },
  {
    type: "normal" as const,
    image: "",
    question: "বাংলাদেশের প্রথম প্রধানমন্ত্রী কে ছিলেন?",
    options: ["জিয়াউর রহমান", "শেখ মুজিবুর রহমান", "এরশাদ", "খালেদা জিয়া"],
    correctAnswer: "শেখ মুজিবুর রহমান",
  },
  {
    type: "multiStatement" as const,
    image: "",
    question: "বাংলাদেশের শিল্প ও সংস্কৃতি সম্পর্কে কোনটি সঠিক?",
    statements: [
      "i. বাংলাদেশের ঐতিহ্যবাহী সংগীত বৈচিত্র্যময়",
      "ii. বাংলাদেশে শিল্পকলার কোনো ঐতিহ্য নেই",
      "iii. বাংলাদেশের নৃত্য ও নাটক বিশ্বখ্যাত",
    ],
    questionEnd: "নিচের কোনটি সঠিক?",
    options: ["A. i & ii", "B. i & iii", "C. শুধুমাত্র ii", "D. শুধুমাত্র iii"],
    correctAnswer: "B. i & iii",
  },
]
